#!/usr/bin/env python3
"""
make_emulator.py - turn a .ds2502 clone dump into a ready-to-flash
DS2502 *emulator* Arduino sketch (OneWireHub library).

Why an emulator?
    The 64-bit ROM ID of a real DS2502 is factory-lasered and can never be
    changed, so a hardware clone always has a different ROM ID.  Many hosts
    (e.g. printers) validate the ROM ID or a data signature derived from it
    and reject the clone.  A microcontroller emulating the DS2502 can present
    the ORIGINAL ROM ID together with the original data + status - a complete
    1:1 impersonation on the 1-Wire bus.

Usage:
    python3 make_emulator.py <dump.ds2502> [output_dir]

Produces:  <output_dir>/ds2502_emulator/ds2502_emulator.ino
Supports:  ESP32 (any classic GPIO) and ATtiny85 (PB2) out of the box.
Requires:  OneWireHub library (Arduino IDE -> Library Manager -> "OneWireHub")
"""

import json
import os
import sys
import time


def crc8(buf, seed=0):
    for b in buf:
        d = b
        for _ in range(8):
            mix = (seed ^ d) & 1
            seed >>= 1
            if mix:
                seed ^= 0x8C
            d >>= 1
    return seed


def load_dump(path):
    """Accept a .ds2502/.json dump or a raw 128-byte .bin (data only)."""
    raw = open(path, "rb").read()
    try:
        j = json.loads(raw.decode("utf-8"))
        data = bytes.fromhex(j["data"])
        stat = bytes.fromhex(j.get("status", "FF" * 7 + "00"))
        rom = bytes.fromhex(j["rom"]) if j.get("rom") else b""
    except (UnicodeDecodeError, json.JSONDecodeError):
        if len(raw) != 128:
            raise ValueError(f"{path}: not a clone dump and not a "
                             f"128-byte bin (size {len(raw)})")
        data, stat, rom = raw, bytes([0xFF] * 7 + [0x00]), b""
    if len(data) != 128 or len(stat) != 8:
        raise ValueError(f"bad lengths: data {len(data)} B (need 128), "
                         f"status {len(stat)} B (need 8)")
    if rom:
        if len(rom) != 8:
            raise ValueError(f"ROM must be 8 bytes, got {len(rom)}")
        if crc8(rom[:7]) != rom[7]:
            raise ValueError("ROM CRC8 check failed - corrupted dump?")
        if rom[0] not in (0x09, 0x11, 0x91):
            print(f"WARNING: family code {rom[0]:02X}h is not a "
                  "DS2502/DS2501 family code", file=sys.stderr)
    return rom, data, stat


def c_array(data, per_line=16, indent="    "):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def generate_sketch(dump_path, out_dir="."):
    rom, data, stat = load_dump(dump_path)
    if not rom:
        # data-only dump: fabricate a ROM ID (host will see THIS id!)
        rom = bytes([0x09, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06])
        rom += bytes([crc8(rom)])
        print("WARNING: dump has no ROM ID - using a made-up one. If the "
              "host checks the ROM ID, re-save the dump from the ORIGINAL "
              "chip!", file=sys.stderr)

    warns = []
    if stat[5] != 0xFF or stat[6] != 0xFF:
        warns.append(f"status bytes 05h/06h are {stat[5]:02X} {stat[6]:02X} "
                     "(emulator always reports FF FF)")
    if stat[7] != 0x00:
        warns.append(f"status byte 07h is {stat[7]:02X} "
                     "(emulator always reports 00)")

    rom_c = ", ".join(f"0x{b:02X}" for b in rom[:7])
    used_pages = [p for p in range(4)
                  if any(b != 0xFF for b in data[p * 32:(p + 1) * 32])]
    warn_c = "".join(f"\n//   WARNING: {w}" for w in warns)

    sketch = f"""// ============================================================
//  DS2502 EMULATOR  -  generated by DS2502_Tool make_emulator.py
//  {time.strftime('%Y-%m-%d %H:%M:%S')}   from: {os.path.basename(dump_path)}
//
//  Emulated ROM ID : {rom.hex().upper()}   (family {rom[0]:02X}h)
//  Data            : 128 bytes, pages used: {used_pages or 'none'}
//  Status          : {' '.join(f'{b:02X}' for b in stat)}{warn_c}
//
//  Library: OneWireHub  (Arduino IDE -> Library Manager -> "OneWireHub")
//
//  Wiring (the emulator REPLACES the DS2502 chip):
//    host DATA contact -> PIN_ONEWIRE      (direct, no resistor needed;
//                                           the host provides the pull-up)
//    host GND  contact -> MCU GND          (common ground is essential!)
//    MCU power         -> its own 3.3 V supply (the emulator cannot use
//                          1-Wire parasite power like the real chip)
//
//  ESP32   : PIN_ONEWIRE = GPIO4  (3.3 V logic - matches most hosts)
//  ATtiny85: PIN_ONEWIRE = PB2 (physical pin 7), run at 8 or 16 MHz,
//            power the ATtiny at the SAME voltage as the host bus.
// ============================================================
#include "OneWireHub.h"
#include "DS2502.h"

#if defined(ARDUINO_ARCH_ESP32)
constexpr uint8_t PIN_ONEWIRE = 4;   // any classic GPIO is fine
#elif defined(__AVR_ATtiny85__) || defined(__AVR_ATtiny45__)
constexpr uint8_t PIN_ONEWIRE = 2;   // PB2 = physical pin 7
#else
constexpr uint8_t PIN_ONEWIRE = 8;   // Uno/Nano fallback
#endif

auto hub  = OneWireHub(PIN_ONEWIRE);
auto ds2502 = DS2502({rom_c});   // CRC byte is computed automatically

// ---- original chip content (from the clone dump) ----
const uint8_t DUMP_DATA[128] = {{
{c_array(data)}
}};
const uint8_t DUMP_STATUS[8] = {{
{c_array(stat, 8)}
}};

void setup()
{{
#if defined(ARDUINO_ARCH_ESP32)
    Serial.begin(115200);
    Serial.println("DS2502 emulator - ROM {rom.hex().upper()}");
#endif
    // preload data page by page; all-FF pages are skipped so the
    // page-used bits in status byte 0 stay exactly like the original
    for (uint8_t page = 0; page < 4; page++)
    {{
        bool used = false;
        for (uint8_t i = 0; i < 32; i++)
            if (DUMP_DATA[page * 32 + i] != 0xFF) {{ used = true; break; }}
        if (used)
            ds2502.writeMemory(&DUMP_DATA[page * 32], 32, page * 32);
    }}
    // preload status bytes 00h-04h (WP/used bitmap + page redirection).
    // Emulator starts at FF and writeStatus ANDs, so this reproduces the
    // original values exactly.  Bytes 05h,06h stay FF and 07h stays 00.
    for (uint8_t i = 0; i < 5; i++)
        ds2502.writeStatus(i, DUMP_STATUS[i]);

    hub.attach(ds2502);
}}

void loop()
{{
    hub.poll();
}}
"""
    sketch_dir = os.path.join(out_dir, "ds2502_emulator")
    os.makedirs(sketch_dir, exist_ok=True)
    ino = os.path.join(sketch_dir, "ds2502_emulator.ino")
    with open(ino, "w") as f:
        f.write(sketch)
    return ino, rom, warns


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    out_dir = sys.argv[2] if len(sys.argv) > 2 else "."
    ino, rom, warns = generate_sketch(sys.argv[1], out_dir)
    print(f"Emulator sketch written: {ino}")
    print(f"Emulated ROM ID        : {rom.hex().upper()}")
    for w in warns:
        print(f"WARNING: {w}")
    print("\nNext steps:")
    print("  1. Arduino IDE -> Library Manager -> install 'OneWireHub'")
    print("  2. Open the sketch, select your board (ESP32 / ATtiny85)")
    print("  3. Flash, then wire DATA->PIN_ONEWIRE and GND->GND")


if __name__ == "__main__":
    main()
